sudo: required
services:
  - docker

before_install:
  - docker build -t rayzol/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rayzol/react-test npm test

after_success:
 - docker build -t rayzol/multi-client ./client
 - docker build -t rayzol/multi-nginx ./nginx
 - docker build -t rayzol/multi-server ./server
 - docker build -t rayzol/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push rayzol/multi-client
 - docker push rayzol/multi-nginx
 - docker push rayzol/multi-server
 - docker push rayzol/multi-worker
#
#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
